### ISSUE TITLE
Suggestion/Request - Allow for Modification of the applied .MCA Header

### ISSUE THREAD

**Issue by RTHKKona** [onepiecefreak3/MCAConverter#4]
Hello! 

I have been having some success with your mcaconverter project but I have a suggestion and an request. I am currently trying to make a tool that extracts the .mca headers from MHGU files but the actual conversion of wav to .mca would be with this app. The issue lies in the first 120bytes of the .mca files as there is a mismatch of magic number and other Capcom metadata that would make the output on vgmstream as "Capcom .ADPCM Header". 

So my suggestion is, would it be possible to adjust the header application system when encoding the wav into .mca file? And if you are unwilling to do so, am I permitted to make a module for my modkit with your .exe/project? I will gladly give you the credit for this.

Here's my [github repo](https://github.com/RTHKKona/Hand_Modkit) for the project.

**Comment by onepiecefreak3** [comment]
I'm unsure how I would make it possible to adjust the header externally. The tool should support the new header structure directly instead. But I have no intention to expand the tool currently.

The code is free to integrate and use in other tools, as long as you give credit, either via name or direct link to this repo.

Good luck.
